#!/bin/bash

# Install jq and update awscli
apt install jq -y
apt install awscli -y

# Get Instance ID and Region
INSTANCE_ID=`curl http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null`
REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document 2>/dev/null | jq -r .region`

# Choose the leader Instance
LEADERINSTANCE='i-0c3fde389cfea8de7'
#LEADERINSTANCE=`aws deploy list-deployment-targets --deployment-id $DEPLOYMENT_ID --region $REGION --max-items 1000 | jq -r '.targetIds | .[]' | sort | head -1`

# check if the current instance is LEADERINSTANCE
if [ "$INSTANCE_ID" = "$LEADERINSTANCE" ]; then
  # your custom code goes here which should run only in one instance
fi
  echo $INSTANCE_ID >> /tmp/temp1file.txt
  echo $DEPLOYMENT_ID >> /tmp/tempfile.txt
